dependencies {
    implementation project(':crimp-common')
    implementation project(':crimp-core')
    implementation project(':crimp-domain')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework:spring-web'

    // OAuth ID Token 검증 (JWKS + RS256)
    implementation 'org.springframework.security:spring-security-oauth2-jose'
    implementation 'org.springframework.security:spring-security-oauth2-resource-server'
}
