dependencies {
    implementation project(':crimp-common')
    implementation project(':crimp-core')
    implementation project(':crimp-domain')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework:spring-web'
}
