import { StyleSheet } from 'react-native';

import {
  fontFamily,
  fontSize,
  fontWeight,
  letterSpacing,
  radius,
  space,
  withAlpha,
  type Theme,
} from '@/lib/tokens';

export function makeProfileStyles(theme: Theme) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.bg,
    },
    center: {
      alignItems: 'center',
      justifyContent: 'center',
      padding: space[6],
      gap: space[3],
    },
    scrollContent: {
      paddingHorizontal: space[5],
      paddingTop: space[6],
      paddingBottom: space[14],
      gap: space[5],
    },
    muted: {
      fontFamily,
      fontSize: fontSize.body,
      color: theme.text3,
    },
    heading: {
      fontFamily,
      fontSize: fontSize.title,
      fontWeight: fontWeight.bold,
      color: theme.text,
    },
    headerEyebrowBlock: {
      gap: space[1],
    },
    eyebrow: {
      fontFamily,
      fontSize: fontSize.caption,
      fontWeight: fontWeight.semibold,
      color: theme.text3,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[4],
    },
    avatar: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: theme.accent.base,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      fontFamily,
      fontSize: 28,
      fontWeight: fontWeight.extrabold,
      letterSpacing: -1.12,
      color: theme.accent.on,
      includeFontPadding: false,
    },
    headerRowBody: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    nicknameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[2],
      minWidth: 0,
    },
    nickname: {
      flexShrink: 1,
      fontFamily,
      fontSize: 22,
      fontWeight: fontWeight.extrabold,
      letterSpacing: -0.66,
      color: theme.text,
    },
    editIconButton: {
      width: 36,
      height: 36,
      borderRadius: radius.full,
      backgroundColor: theme.subtle,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bioText: {
      fontFamily,
      fontSize: 13,
      fontWeight: fontWeight.medium,
      color: theme.text3,
    },
    statsRow: {
      flexDirection: 'row',
      gap: space[5],
      flexWrap: 'wrap',
    },
    statPill: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: space[1],
    },
    statPillValue: {
      fontFamily,
      fontSize: 13,
      fontWeight: fontWeight.extrabold,
      color: theme.text,
      letterSpacing: -0.13,
      includeFontPadding: false,
    },
    statPillLabel: {
      fontFamily,
      fontSize: 13,
      fontWeight: fontWeight.semibold,
      color: theme.text3,
    },
    heroCard: {
      backgroundColor: theme.subtle,
      borderRadius: radius.xl,
      padding: space[5],
      gap: space[2],
    },
    heroCaption: {
      fontFamily,
      fontSize: fontSize.caption,
      fontWeight: fontWeight.bold,
      color: theme.text3,
      letterSpacing: -0.12,
    },
    heroRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: space[4],
    },
    heroNumber: {
      fontFamily,
      fontSize: 80,
      fontWeight: fontWeight.extrabold,
      letterSpacing: -4.8,
      lineHeight: 80 * 0.9,
      color: theme.accent.base,
      includeFontPadding: false,
    },
    heroSubtext: {
      fontFamily,
      fontSize: fontSize.caption,
      fontWeight: fontWeight.medium,
      color: theme.text3,
      flexShrink: 1,
    },
    card: {
      backgroundColor: theme.subtle,
      borderRadius: radius.xl,
      padding: space[5],
      gap: space[3],
    },
    cardTitle: {
      fontFamily,
      fontSize: fontSize.title,
      fontWeight: fontWeight.bold,
      letterSpacing: letterSpacing.title,
      color: theme.text,
    },
    cardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[3],
    },
    cardRowLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[3],
      minWidth: 0,
    },
    gymIconCircle: {
      width: 36,
      height: 36,
      borderRadius: radius.full,
      backgroundColor: theme.chip,
      alignItems: 'center',
      justifyContent: 'center',
    },
    gymLabelBlock: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    gymLabel: {
      fontFamily,
      fontSize: fontSize.body,
      fontWeight: fontWeight.semibold,
      color: theme.text,
      letterSpacing: letterSpacing.body,
    },
    gymLabelMuted: {
      color: theme.text3,
      fontWeight: fontWeight.medium,
    },
    gymBrand: {
      fontFamily,
      fontSize: fontSize.caption,
      fontWeight: fontWeight.medium,
      color: theme.text3,
    },
    ctaRow: {
      flexDirection: 'row',
      gap: space[2],
    },
    ctaButton: {
      flex: 1,
      paddingVertical: space[3],
      paddingHorizontal: space[4],
      borderRadius: radius.lg,
      backgroundColor: theme.accent.base,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ctaButtonPressed: {
      opacity: 0.85,
    },
    ctaButtonDisabled: {
      opacity: 0.5,
    },
    ctaButtonLabel: {
      fontFamily,
      fontSize: fontSize.body,
      fontWeight: fontWeight.bold,
      color: theme.accent.on,
      letterSpacing: letterSpacing.body,
    },
    ctaButtonDanger: {
      paddingVertical: space[3],
      paddingHorizontal: space[4],
      borderRadius: radius.lg,
      backgroundColor: withAlpha(theme.semantic.danger, 0.1),
      alignItems: 'center',
      justifyContent: 'center',
    },
    ctaButtonDangerLabel: {
      fontFamily,
      fontSize: fontSize.body,
      fontWeight: fontWeight.bold,
      color: theme.semantic.danger,
      letterSpacing: letterSpacing.body,
    },
    savingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space[2],
      paddingTop: space[1],
    },
    inlineErrorBox: {
      backgroundColor: withAlpha(theme.semantic.danger, 0.08),
      borderRadius: radius.md,
      padding: space[3],
      gap: space[1],
    },
    inlineErrorTitle: {
      fontFamily,
      fontSize: 13,
      fontWeight: fontWeight.bold,
      color: theme.semantic.danger,
    },
    logoutButton: {
      paddingVertical: space[3],
      paddingHorizontal: space[4],
      borderRadius: radius.lg,
      backgroundColor: theme.subtle,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoutButtonPressed: {
      opacity: 0.85,
    },
    logoutButtonDisabled: {
      opacity: 0.5,
    },
    logoutButtonLabel: {
      fontFamily,
      fontSize: fontSize.body,
      fontWeight: fontWeight.semibold,
      color: theme.text2,
      letterSpacing: letterSpacing.body,
    },
    deleteAccountButton: {
      paddingVertical: space[3],
      paddingHorizontal: space[4],
      borderRadius: radius.lg,
      backgroundColor: withAlpha(theme.semantic.danger, 0.08),
      alignItems: 'center',
      justifyContent: 'center',
    },
    deleteAccountButtonPressed: {
      opacity: 0.85,
    },
    deleteAccountButtonDisabled: {
      opacity: 0.5,
    },
    deleteAccountButtonLabel: {
      fontFamily,
      fontSize: fontSize.body,
      fontWeight: fontWeight.semibold,
      color: theme.semantic.danger,
      letterSpacing: letterSpacing.body,
    },
    errorBox: {
      margin: space[5],
      backgroundColor: withAlpha(theme.semantic.danger, 0.08),
      borderRadius: radius.lg,
      padding: space[4],
      gap: space[1],
    },
    errorTitle: {
      fontFamily,
      fontSize: fontSize.body,
      fontWeight: fontWeight.bold,
      color: theme.semantic.danger,
    },
  });
}

export type ProfileStyles = ReturnType<typeof makeProfileStyles>;
